jQuery(document).ready(function($){$.ajax({url:"http://auth.geeksforgeeks.org/gfgLink.php",type:'GET',dataType:"jsonp",data:{'link':window.location.href},success:function(responseData,textStatus,jqXHR){$("#practice").html(responseData.markup);$("#company_tags").html(responseData.tags)},error:function(jqXHR,textStatus,errorThrown){console.log('Response: '+jqXHR)}});$.ajax({url:"http://auth.geeksforgeeks.org/plugin.php",method:"POST",dataType:"json",data:{post_id:$("#ratePlugin").attr("pid"),url:window.location.href},xhrFields:{withCredentials:!0},success:function(response){$("#ratePlugin").html(response.rate);$("#markPlugin").html(response.mark)},complete:function(){$(".box").click(function(){rrequest({post_id:$("#ratePlugin").attr("pid"),post_title:$("#ratePlugin").attr("ptitle"),rating:$(this).attr("rating"),url:window.location.href})});$(".mark").click(function(){mrequest({post_id:$("#markPlugin").attr("pid"),post_title:$("#markPlugin").attr("ptitle"),op:$(this).attr("id"),url:window.location.href})})}});function rrequest(payload){$.ajax({url:"http://auth.geeksforgeeks.org/gfgRatings.php",method:"POST",dataType:"html",data:payload,xhrFields:{withCredentials:!0},success:function(response){$("#ratePlugin").html(response)},complete:function(){$(".box").click(function(){rrequest({post_id:$("#ratePlugin").attr("pid"),post_title:$("#ratePlugin").attr("ptitle"),rating:$(this).attr("rating"),url:window.location.href})})}})}
function mrequest(payload){$.ajax({url:"http://auth.geeksforgeeks.org/gfgMarking.php",method:"POST",dataType:"html",data:payload,xhrFields:{withCredentials:!0},success:function(response){$("#markPlugin").html(response)},complete:function(){$(".mark").click(function(){mrequest({post_id:$("#markPlugin").attr("pid"),post_title:$("#markPlugin").attr("ptitle"),op:$(this).attr("id"),url:window.location.href})})}})}
$('#comment').on('click',function(){$.ajax({type:"GET",url:"http://geeksforgeeks.disqus.com/embed.js",dataType:"script",cache:!0});$(this).fadeOut()});if(window.location.href.indexOf('#comment')>-1){jQuery('#comment').click()}
window.selectnav=(function(){"use strict";var selectnav=function(element,options){element=document.getElementById(element);if(!element){return}
if(!islist(element)){return}
if(!('insertAdjacentHTML' in window.document.documentElement)){return}
document.documentElement.className+=" js";var o=options||{},activeclass=o.activeclass||'active',autoselect=typeof(o.autoselect)==="boolean"?o.autoselect:!0,nested=typeof(o.nested)==="boolean"?o.nested:!0,indent=o.indent||"→",label=o.label||"- Navigation -",level=0,selected=" selected ";element.insertAdjacentHTML('afterend',parselist(element));var nav=document.getElementById(id());if(nav.addEventListener){nav.addEventListener('change',goTo)}
if(nav.attachEvent){nav.attachEvent('onchange',goTo)}
return nav;function goTo(e){var targ;if(!e)e=window.event;if(e.target)targ=e.target;else if(e.srcElement)targ=e.srcElement;if(targ.nodeType===3)
targ=targ.parentNode;if(targ.value)window.location.href=targ.value}
function islist(list){var n=list.nodeName.toLowerCase();return(n==='ul'||n==='ol')}
function id(nextId){for(var j=1;document.getElementById('selectnav'+j);j++);return(nextId)?'selectnav'+j:'selectnav'+(j-1)}
function parselist(list){level++;var length=list.children.length,html='',prefix='',k=level-1;if(!length){return}
if(k){while(k--){prefix+=indent}
prefix+=" "}
for(var i=0;i<length;i++){var link=list.children[i].children[0];if(typeof(link)!=='undefined'){var text=link.innerText||link.textContent;var isselected='';if(activeclass){isselected=link.className.search(activeclass)!==-1||link.parentNode.className.search(activeclass)!==-1?selected:''}
if(autoselect&&!isselected){isselected=link.href===document.URL?selected:''}
html+='<option value="'+link.href+'" '+isselected+'>'+prefix+text+'</option>';if(nested){var subElement=list.children[i].children[1];if(subElement&&islist(subElement)){html+=parselist(subElement)}}}}
if(level===1&&label){html='<option value="">'+label+'</option>'+html}
if(level===1){html='<select class="selectnav" id="'+id(!0)+'">'+html+'</select>'}
level--;return html}};return function(element,options){selectnav(element,options)}})();selectnav('menu-top',{label:'Menu',nested:!0,indent:'-'});(function(){var cx='009682134359037907028:tj6eafkv_be';var gcse=document.createElement('script');gcse.type='text/javascript';gcse.async=!0;gcse.src=(document.location.protocol=='https:'?'https:':'http:')+'//cse.google.com/cse.js?cx='+cx;var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(gcse,s)})();$.ajax({type:'GET',dataType:"json",url:"http://auth.geeksforgeeks.org/profileLink.php",xhrFields:{withCredentials:!0},success:function(responseData,textStatus,jqXHR){document.getElementById("profile").innerHTML=responseData.data},error:function(responseData,textStatus,errorThrown){console.log('HTTP Status : '+textStatus)}})})
